name: DebianRepository
on: [push]

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Create Debian repository test
        uses: ./
        env: 
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}     
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}     
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}          
          REPOSITORY: './docs/debian'
          NAME: 'debcvescan'
          ARCH: 'amd64'
          OS: 'linux'
          CODENAME: 'buster'
