name: DebianRepository
on: [push]

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Create Debian repository test2
        uses: ./
        with:
          who-to-greet: 'hello world'
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
